FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags='-s -w' -o /out/signal-aws-collector ./cmd/signal-aws-collector

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/signal-aws-collector /signal-aws-collector
USER nonroot:nonroot
ENTRYPOINT ["/signal-aws-collector"]